# Name of the workflow
name: Lighthouse Tests

# Specifies when to trigger the workflow
on:
  push: # Triggered on push events
    branches: # Specify the branches to trigger the workflow on
      - main # Triggered when changes are pushed to the main branch
      - feature/sharon # Triggered when changes are pushed to the main branch
# Defines the jobs to be executed in this workflow
jobs:
  lighthouse-test: # Name of the job
    runs-on: ubuntu-latest # Specifies the operating system to run the job on

    steps: # Defines the steps to be executed in the job
    - name: Checkout Repository # Name of the step
      uses: actions/checkout@v4 # Action to checkout the repository

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: "14.x"

    - name: Install NodeModules
      run: npm install @babel/core @babel/cli @babel/preset-env --save-dev && npm ci --prefix ./wedding-website 

    - name: Install LH Dependencies
      run: npm i -g http-server @lhci/cli --prefix ./wedding-website

    - name: Build
      run: npm run build --prefix ./wedding-website

    - name: LighthouseCI
      run: lhci autorun --prefix ./wedding-website
